@CoffeeShop.Gateway_HostAddress = https://localhost:7066

GET {{CoffeeShop.Gateway_HostAddress}}/gateway/Customer/
Accept: application/json

###

GET {{CoffeeShop.Gateway_HostAddress}}/gateway/Customer/1
Accept: application/json

###

GET {{CoffeeShop.Gateway_HostAddress}}/gateway/Menu/
Accept: application/json

###

GET {{CoffeeShop.Gateway_HostAddress}}/gateway/Menu/1
Accept: application/json

###
